version: '3'
networks:
  tp-lin2:
    ipam:
      config:
        - subnet: 172.18.0.0/24
services:
  lin2-server:
    build:
      context: ./api-server/
      dockerfile: Dockerfile
    container_name: lin2-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      tp-lin2:
        ipv4_address: 172.18.0.10
  lin2-client:
    build:
      context: ./api-client/
      dockerfile: Dockerfile
    container_name: lin2-client
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      tp-lin2:
        ipv4_address: 172.18.0.20
    depends_on:
      - "lin2-server"
